apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-key
              key: secret-access-key
      command: [ "sleep", "3600" ]
  restartPolicy: Never
