# Mimir Temp
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimir-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  hostPath:
    path: /data/mimir-temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-pvc
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
