#!/usr/bin/env bash
# ==============================================================================
# scripts/install_HAProxy.sh
# Installs HAProxy Kubernetes Ingress Controller into kube-system.
#
# Run standalone:   sudo bash scripts/install_HAProxy.sh
# Run via all:      called automatically by install_all.sh
# ==============================================================================
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

require_root
require_helm

# Fix: Ensure KUBECONFIG is available to Helm, even if sudo reset env vars
if [[ -z "${KUBECONFIG:-}" ]]; then
  if [[ -f "/root/.kube/config" ]]; then
    export KUBECONFIG="/root/.kube/config"
  elif [[ -f "/var/lib/k0s/pki/admin.conf" ]]; then
    export KUBECONFIG="/var/lib/k0s/pki/admin.conf"
  fi
fi

# Fix: Set a default version if the variable is missing from common.sh
: "${HAPROXY_CHART_VERSION:=1.44.0}"

header "Phase 2 — HAProxy Ingress Controller ${HAPROXY_CHART_VERSION}"

# Fix: Ensure repo exists before installing (Idempotency)
info "Updating Helm repositories..."
helm repo add haproxytech https://haproxytech.github.io/helm-charts --force-update
helm repo update haproxytech >/dev/null

HAPROXY_VALUES="${SCRIPT_DIR}/../values/haproxy-values.yaml"

if [[ -f "${HAPROXY_VALUES}" ]]; then
  info "Deploying HAProxy Ingress..."
  # Fix: Increased timeout to 5m to handle potential image pull delays
  helm upgrade --install haproxy-ingress haproxytech/kubernetes-ingress \
    --namespace kube-system \
    --version "${HAPROXY_CHART_VERSION}" \
    --wait --timeout 5m \
    --values "${HAPROXY_VALUES}"
else
  die "HAProxy values file not found: ${HAPROXY_VALUES}"
fi

# Note: The deployment name 'haproxy-ingress-kubernetes-ingress' is the default
# generated by Helm for release 'haproxy-ingress' and chart 'kubernetes-ingress'.
wait_rollout kube-system deployment/haproxy-ingress-kubernetes-ingress 120s

echo ""
success "install_HAProxy.sh complete"
info "HAProxy bound to host ports 80/443 — IngressClass 'haproxy' is default"
echo ""
