# Grafana Values
replicas: 1

admin:
  existingSecret: grafana-admin

persistence:
  enabled: false

grafana.ini:
  analytics:
    reporting_enabled: false
  log:
    mode: console
  users:
    auto_assign_org: true
    auto_assign_org_role: Viewer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        url: http://mimir.monitoring.svc.cluster.local:8080
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
      - name: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi
