fullnameOverride: tempo

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

  persistence:
    enabled: false   # safe since S3 backend

tempo:
  auth_enabled: false

  server:
    http_listen_port: 3200
    grpc_listen_port: 9096

  storage:
    trace:
      backend: s3
      s3:
        region: ${S3_REGION}
        bucket: ${S3_BUCKET}
        prefix: lgtm-prod/tempo/

  metricsGenerator:
    enabled: false

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
